In [1]:
from torch_bert_classify import tmv_torch_bert_classify

C:\Users\macks\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
import pandas as pd
number_data_set = 4
csv_dump = True
epochs = 1
dependent_var = r'Definition-Score'
task_word = r'Definition'
number_class = 3
top_to = 200

df_response_answer = pd.read_csv(r'../data/' + r'Serialized-Def-ELVA.PILOT.PRE-TEST.csv', encoding= 'latin1')
df_response_answer.iloc[:top_to, :].to_csv(r'../data/' + 'Top-to-' + str(top_to) + r'-Serialized-Def-ELVA.PILOT.PRE-TEST.csv', encoding= 'latin1')

bertd = tmv_torch_bert_classify(r'../data/', r'../train/pytorch_advanced/nlp_sentiment_bert/')
# bertd.load_data(r'Serialized-Def-ELVA.PILOT.PRE-TEST.csv', dependent_var, [0, 1], task_word)
bertd.load_data('Top-to-' + str(top_to) + r'-Serialized-Def-ELVA.PILOT.PRE-TEST.csv',
                dependent_var, [0, 1], task_word)
bertd.iloc_split_for_cross_validation(number_data_set = number_data_set)
bertd.modeling_prediction_evaluation_all(r'TORCH_BERT-Def-PRE-All', csv_dump, number_class,
                                         epochs=epochs)
bertd.df_ac_classified_all.to_csv(r'../data/' + 'TORCH_BERT-Classified-Prediction-Def-PRE-All.csv',
                                  encoding= 'latin1')


bert.embeddings.word_embeddings.weight→embeddings.word_embeddings.weight
bert.embeddings.position_embeddings.weight→embeddings.position_embeddings.weight
bert.embeddings.token_type_embeddings.weight→embeddings.token_type_embeddings.weight
bert.embeddings.LayerNorm.gamma→embeddings.LayerNorm.gamma
bert.embeddings.LayerNorm.beta→embeddings.LayerNorm.beta
bert.encoder.layer.0.attention.self.query.weight→encoder.layer.0.attention.selfattn.query.weight
bert.encoder.layer.0.attention.self.query.bias→encoder.layer.0.attention.selfattn.query.bias
bert.encoder.layer.0.attention.self.key.weight→encoder.layer.0.attention.selfattn.key.weight
bert.encoder.layer.0.attention.self.key.bias→encoder.layer.0.attention.selfattn.key.bias
bert.encoder.layer.0.attention.self.value.weight→encoder.layer.0.attention.selfattn.value.weight
bert.encoder.layer.0.attention.self.value.bias→encoder.layer.0.attention.selfattn.value.bias
bert.encoder.layer.0.attention.output.dense.weight→encoder.layer.0.attention.output

----------------
RANDOM SET:  0
Concat Value Len: 150
(tensor([[ 101, 2965, 1996,  ...,    0,    0,    0],
        [ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 2242, 2008,  ...,    0,    0,    0],
        ...,
        [ 101, 1037, 2711,  ...,    0,    0,    0],
        [ 101, 2129, 2057,  ...,    0,    0,    0],
        [ 101, 1996, 2929,  ...,    0,    0,    0]]), tensor([12, 10, 14, 18, 23, 15, 29, 14, 14, 10, 12, 19, 26, 12, 20, 14, 13, 21,
        13, 12, 18, 14, 14, 27, 32, 23, 16, 19, 17, 14]))
tensor([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2,
        0, 1, 0, 1, 0, 0])
['[CLS]', 'to', 'study', 'something', 'closely', 'and', 'carefully', 'd', '##k', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PA

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:56<00:00, 28.12s/it]
C:\Users\macks\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\macks\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Test Data 50 Accuracy: 0.8000
Recall                      0.8000
Precision                   0.6400
F1                          0.7111
Kappa                       0.0000
Quadratic Weighted Kappa    0.0000
dtype: float64
Confusion Matrix:
    0  1  2
0  40  0  0
1   4  0  0
2   6  0  0
----------------
RANDOM SET:  1
Concat Value Len: 150
(tensor([[ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 5577, 2242,  ...,    0,    0,    0],
        [ 101, 2242, 2008,  ...,    0,    0,    0],
        ...,
        [ 101, 1037, 2711,  ...,    0,    0,    0],
        [ 101, 2129, 2057,  ...,    0,    0,    0],
        [ 101, 2619, 2017,  ...,    0,    0,    0]]), tensor([10, 11, 14, 18, 18, 15, 10, 14, 14, 10, 12, 14, 26, 12, 20, 24, 13, 27,
        13, 11, 13, 14, 14, 27, 17, 23, 16, 19, 17, 25]))
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 2,
        0, 1, 0, 1, 0, 2])
['[CLS]', 'describes', 'something', 'stiff', 'or', 'hard', 'to', 'bend', 'd', '##k', '[

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:55<00:00, 27.95s/it]


Test Data 50 Accuracy: 0.6800
Recall                      0.6800
Precision                   0.4624
F1                          0.5505
Kappa                       0.0000
Quadratic Weighted Kappa    0.0000
dtype: float64
Confusion Matrix:
    0  1  2
0  34  0  0
1  10  0  0
2   6  0  0
----------------
RANDOM SET:  2
Concat Value Len: 150
(tensor([[ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 5577, 2242,  ...,    0,    0,    0],
        [ 101, 2129, 2057,  ...,    0,    0,    0],
        ...,
        [ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 5577, 2242,  ...,    0,    0,    0],
        [ 101, 2619, 2017,  ...,    0,    0,    0]]), tensor([10, 11, 16, 11, 18, 15, 10, 14, 14, 10, 12, 14, 16, 12, 20, 24, 13, 27,
        13, 11, 13, 14, 14, 10, 17, 12, 16, 10, 22, 25]))
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 2])
['[CLS]', 'describes', 'something', 'stiff', 'or', 'hard', 'to', 'bend', 'd', '##k', '[

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [01:00<00:00, 30.26s/it]


Test Data 50 Accuracy: 0.7000
Recall                      0.7000
Precision                   0.4900
F1                          0.5765
Kappa                       0.0000
Quadratic Weighted Kappa    0.0000
dtype: float64
Confusion Matrix:
    0  1  2
0  35  0  0
1  10  0  0
2   5  0  0
----------------
RANDOM SET:  3
Concat Value Len: 150
(tensor([[ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 5577, 2242,  ...,    0,    0,    0],
        [ 101, 2129, 2057,  ...,    0,    0,    0],
        ...,
        [ 101, 2000, 2817,  ...,    0,    0,    0],
        [ 101, 5577, 2242,  ...,    0,    0,    0],
        [ 101, 2619, 2017,  ...,    0,    0,    0]]), tensor([10, 11, 16, 11, 18, 15, 10, 24, 11, 14, 20, 14, 16, 21, 31, 24, 14, 27,
        11, 11, 13, 19, 16, 10, 17, 12, 17, 10, 22, 25]))
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 2])
['[CLS]', 'describes', 'something', 'stiff', 'or', 'hard', 'to', 'bend', 'd', '##k', '[

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:57<00:00, 28.99s/it]

Test Data 50 Accuracy: 0.7400
Recall                      0.7400
Precision                   0.5476
F1                          0.6294
Kappa                       0.0000
Quadratic Weighted Kappa    0.0000
dtype: float64
Confusion Matrix:
    0  1  2
0  37  0  0
1   7  0  0
2   6  0  0
----------------
ALL DATA (Macro Average):
         Recall  Precision        F1  Kappa  Quadratic Weighted Kappa
count  4.000000   4.000000  4.000000    4.0                       4.0
mean   0.730000   0.535000  0.616875    0.0                       0.0
std    0.052915   0.078485  0.070878    0.0                       0.0
min    0.680000   0.462400  0.550500    0.0                       0.0
25%    0.695000   0.483100  0.570000    0.0                       0.0
50%    0.720000   0.518800  0.602950    0.0                       0.0
75%    0.755000   0.570700  0.649825    0.0                       0.0
max    0.800000   0.640000  0.711100    0.0                       0.0
----------------
ALL DATA (Micro Average)